version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./ecommerce.db:/app/ecommerce.db
      - ./static:/app/static
    restart: unless-stopped
    environment:
      - FLASK_ENV=production 